baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "engineering focus in a distracted world"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "duffney.io"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "_ cd /duffney.io"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
[params.portrait]
  path = "/img/portrait.jpg"
  alt = "Portrait"


  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/joshduffney"
  [[params.social]]
    name = "github"
    url  = "https://github.com/Duffney"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/joshduffney/"
  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/3934865/joshduffney"


  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"

  [[menu.main]]
    name = "start here"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/start-here/"
    weight = -100

[[menu.main]]
    identifier = "essays"
    name       = "essays"
    url        = "/categories/essays/"

  [[menu.main]]
    identifier = "links"
    name       = "links"
    url        = "/links"
  
  [[menu.main]]
    identifier = "tweets"
    name       = "tweets"
    url        = "/tweets"